PSU.Site/Areas/Instructor/Controllers/NewbornController.cs
//-----------------------------------------------------------------------
// <copyright file= "NewbornController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018-03-07 20:34:09
// Modified by:
// Description: Instructor-Newborn-控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Instructor;
using PSU.Model.Areas.Instructor.Newborn;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Instructor
{
    [Area("Instructor")]
    [Authorize(Policy = "Instructor")]
    public class NewbornController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly INewbornService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public NewbornController(INewbornService service, ILogger<NewbornController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 新生报名情况页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        /// <summary>
        /// 新生宿舍选择页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Dormitory()
        {
            return View();
        }

        /// <summary>
        /// 新生信息页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }

        /// <summary>
        /// 新生详细信息页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var webModel = await _service.GetStudentAsync(Convert.ToInt64(id), _context);
                return View(webModel);
            }
            return Redirect("Information");
        }

        #endregion

        #region Service

        /// <summary>
        /// 新生报名信息页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchRegister(string search)
        {
            RegisterViewModel webModel = JsonUtility.ToObject<RegisterViewModel>(search);

            webModel = await _service.SearchRegisterAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SMajorClass) && string.IsNullOrEmpty(webModel.SDate);

            var returnData = new
            {
                data = webModel.RegisterList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 新生预定寝室信息页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchDormitory(string search)
        {
            DormitoryViewModel webModel = JsonUtility.ToObject<DormitoryViewModel>(search);

            webModel = await _service.SearchDormitoryAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SStudent) && string.IsNullOrEmpty(webModel.SBuilding);

            var returnData = new
            {
                data = webModel.DormitoryList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 新生信息页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchInformation(string search)
        {
            InformationViewModel webModel = JsonUtility.ToObject<InformationViewModel>(search);

            webModel = await _service.SearchStudentAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SId) && string.IsNullOrEmpty(webModel.SMajorClass);

            var returnData = new
            {
                data = webModel.StudentList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        #endregion
    }
}

PSU.Site/Areas/Instructor/Controllers/QuestionController.cs
//-----------------------------------------------------------------------
// <copyright file= "QuestionController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018/3/7 星期三 13:13:34
// Modified by:
// Description: Instructor-Question-控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Instructor;
using PSU.Model.Areas.Instructor.Question;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Instructor
{
    [Area("Instructor")]
    [Authorize(Policy = "Instructor")]
    public class QuestionController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IQuestionService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public QuestionController(IQuestionService service, ILogger<QuestionController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 学生疑问数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }

        /// <summary>
        /// 回复疑问信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Reply(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var webModel = await _service.GetQuestionAsync(Convert.ToInt64(id), _context);
                return View(webModel);
            }
            return Redirect("Information");
        }

        #endregion

        #region Service

        /// <summary>
        /// 学生疑问页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchQuestion(string search)
        {
            QuestionViewModel webModel = JsonUtility.ToObject<QuestionViewModel>(search);

            webModel = await _service.SearchQuestionAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SDateTime) && webModel.IsReply == -1;

            var returnData = new
            {
                data = webModel.QuestionList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 回复学生疑问信息页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Reply(QuestionReplyViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    return Json(new
                    {
                        success = false,
                        msg = "回复学生疑问信息失败,问题编号为空"
                    });
                }
                else
                {
                    //Update Question
                    flag = await _service.ReplyQuestionAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "回复学生疑问信息成功" : "回复学生疑问信息失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        #endregion
    }
}

PSU.Site/Areas/Student/Controllers/UserController.cs
//-----------------------------------------------------------------------
// <copyright file= "UserController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018-03-08 20:56:47
// Modified by:
// Description: Student-User控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Student;
using PSU.Model.Areas.Student;
using PSU.Utility;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Student
{
    [Area("Student")]
    [Authorize(Policy = "Student")]
    public class UserController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IUserService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserController(IUserService service, ILogger<UserController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 个人中心
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var webModel = await _service.GetStudentAsync(CurrentUser.UserId, _context);
            return View(webModel);
        }

        #endregion

        #region Service

        /// <summary>
        /// 学生编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditProfile(ProfileViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;

                //Update Student
                flag = await _service.UpdateStudentAsync(webModel, _context);

                return Json(new
                {
                    success = flag,
                    msg = flag ? "个人信息编辑成功" : "个人信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        #endregion
    }
}

PSU.Site/Areas/Instructor/Views/Shared/_Layout.cshtml
@using PSU.Utility
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - 一世计科</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/template/dataTables.bootstrap.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/lib/Ionicons/css/ionicons.css" rel="stylesheet" />
        <link href="~/css/template/AdminLTE.css" rel="stylesheet" />
        <link href="~/css/template/skins/skin-green.css" rel="stylesheet" />
        <link href="~/css/template/bootstrap-datepicker.css" rel="stylesheet" />
        <link href="~/css/template/pace.css" rel="stylesheet" />
        <link href="~/css/template/green.css" rel="stylesheet" />
        <link href="~/css/view/layout.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute">
        <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
              asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute">
        <link href="http://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet"
              asp-fallback-href="~/lib/Ionicons/css/ionicons.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/css/view/layout.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>

    @RenderSection("styles", false)

</head>
<body class="sidebar-mini skin-green fixed" style="height: auto; min-height: 100%;">
    <div class="wrapper" style="height: auto; min-height: 100%;">
        <!-- 头部 -->
        <header class="main-header">
            <a asp-area="Instructor" asp-controller="Home" asp-action="Index" class="logo">
                <span class="logo-mini">
                    <b>一世</b>
                </span>
                <span class="logo-lg">
                    <i class="fa fa-leaf"></i>
                    <b style="font-family:KaiTi">
                        一世计科
                        <sub style="font-family:Consolas">Yishi</sub>
                    </b>
                </span>
            </a>
            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">切换菜单</span>
                </a>
                <div class="navbar-custom-menu">
                    <form asp-area="" asp-controller="Secret" asp-action="Logout" method="post">
                        <ul class="nav navbar-nav">
                            <li class="user user-menu">
                                <a asp-area="Instructor" asp-controller="User" asp-action="Profile">
                                    <img src="~/images/template/user2-160x160.jpg" class="user-image" alt="User Image">
                                    <span class="hidden-xs">@CurrentUser.UserName</span>
                                </a>
                            </li>
                            <li>
                                <button type="submit" class="btn btn-link navbar-btn text-white btn-logout ">
                                    <i class="fa fa-sign-out"></i>
                                    <span>退出</span>
                                </button>
                            </li>
                        </ul>
                    </form>
                </div>
            </nav>
        </header>

        <!-- 左侧菜单栏 -->
        <aside class="main-sidebar">
            <section class="sidebar" style="height:auto;">
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">菜单 Menu</li>
                    <li class="@(ViewData["NavTitle"].ToString() == "数据全局概览"?"active":"")">
                        <a asp-area="Instructor" asp-controller="Home" asp-action="Index">
                            <i class="fa fa-dashboard"></i> <span> 数据全局概览 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "我的班级管理"?"active":"")">
                        <a asp-area="Instructor" asp-controller="User" asp-action="Classes">
                            <i class="fa fa-archive"></i> <span> 我的班级管理 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "新生疑问管理"?"active":"")">
                        <a asp-area="Instructor" asp-controller="Question" asp-action="Information">
                            <i class="fa fa-question-circle"></i> <span> 新生疑问管理 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "新生报名情况"?"active":"")">
                        <a asp-area="Instructor" asp-controller="Newborn" asp-action="Register">
                            <i class="fa fa-check-circle"></i> <span> 新生报名情况 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "新生宿舍选择"?"active":"")">
                        <a asp-area="Instructor" asp-controller="Newborn" asp-action="Dormitory">
                            <i class="fa fa-home"></i> <span> 新生宿舍选择 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "新生数据管理"?"active":"")">
                        <a asp-area="Instructor" asp-controller="Newborn" asp-action="Information">
                            <i class="fa fa-info-circle"></i> <span> 新生数据管理 </span>
                        </a>
                    </li>
                    <li class="@(ViewData["NavTitle"].ToString() == "个人账户管理"?"active":"")">
                        <a asp-area="Instructor" asp-controller="User" asp-action="Profile">
                            <i class="fa fa-user-circle-o"></i> <span> 个人账户管理 </span>
                        </a>
                    </li>
                </ul>
            </section>
        </aside>

        <!-- 页面主体内容 -->
        <div class="content-wrapper">
            @RenderBody()
        </div>

        <!-- 尾部版权 -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    Powered By <span class="text-blue">Run2948</span>
                    <a href="https://github.com/Run2948" target="_blank">
                        <i class="fa fa-github text-black"></i>
                    </a>
                    <a href="https://gitee.com/zhuJR" target="_blank">
                        <i class="fa fa-star-half-o text-black"></i>
                    </a>
                    <a href="https://weibo.com/u/3568138617" target="_blank">
                        <i class="fa fa-weibo text-danger"></i>
                    </a>
                </div>
                <p>
                    Copyright  &copy; 2017 - @DateTime.Now.Year <a href="javascript:void(0)"> 一世计科 </a> 版权所有
                </p>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/javascript/template/jquery.dataTables.js"></script>
        <script src="~/javascript/template/dataTables.bootstrap.js"></script>
        <script src="~/javascript/template/bootstrap-datepicker.js"></script>
        <script src="~/javascript/template/bootstrap-datepicker.zh-CN.min.js"></script>
        <script src="~/javascript/template/jquery.slimscroll.js"></script>
        <script src="~/javascript/template/adminlte.js"></script>
        <script src="~/javascript/template/pace.js"></script>
        <script src="~/javascript/template/bootbox.min.js"></script>
        <script src="~/javascript/template/icheck.js"></script>
        <script src="~/javascript/view/layout.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js">
        </script>
        <script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js">
        </script>
        <script src="https://cdn.bootcss.com/iCheck/1.0.1/icheck.min.js"
                asp-fallback-src="~/javascript/template/icheck.min.js">
        </script>
        <script src="~/javascript/view/layout.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", false)

</body>
</html>