PSU.Site/Areas/Administrator/Controllers/AdmissionController.cs
//-----------------------------------------------------------------------
// <copyright file= "AdmissionController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018/2/10 星期六 15:44:13
// Modified by:
// Description: Administrator-Admission控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Administrator;
using PSU.Model.Areas.Administrator.Admission;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Administrator
{
    [Area("Administrator")]
    [Authorize(Policy = "Administrator")]
    public class AdmissionController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IAdmissionService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public AdmissionController(IAdmissionService service, ILogger<AdmissionController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 物品信息编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditGoods(string id)
        {
            GoodsEditViewModel webModel = new GoodsEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载物品相关信息
                webModel = await _service.GetGoodsAsync(Convert.ToInt64(id), _context);
            }

            return View(webModel);
        }

        /// <summary>
        /// 迎新服务编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditService(string id)
        {
            ServiceEditViewModel webModel = new ServiceEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载迎新服务信息
                webModel = await _service.GetServiceAsync(Convert.ToInt64(id), _context);
            }

            return View(webModel);
        }

        /// <summary>
        /// 物品信息
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Goods()
        {
            return View();
        }

        /// <summary>
        /// 学生疑问数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Question()
        {
            return View();
        }

        /// <summary>
        /// 回复疑问信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Reply(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var webModel = await _service.GetQuestionAsync(Convert.ToInt64(id), _context);
                return View(webModel);
            }
            return Redirect("Question");
        }

        /// <summary>
        /// 迎新服务
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Service()
        {
            return View();
        }
        #endregion

        #region Service

        /// <summary>
        /// 删除物品信息数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteGoods(string id)
        {
            bool flag = await _service.DeleteGoodsAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，物品编号：" + id : "数据删除失败，物品编号：" + id
            });
        }

        /// <summary>
        /// 删除迎新服务数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteService(string id)
        {
            bool flag = await _service.DeleteServiceAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，迎新服务编号：" + id : "数据删除失败，迎新服务编号：" + id
            });
        }

        /// <summary>
        /// 物品信息编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditGoods(GoodsEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Data
                    flag = await _service.InsertGoodsAsync(webModel, _context);
                }
                else
                {
                    //Update Data
                    flag = await _service.UpdateGoodsAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "物品信息编辑成功" : "物品信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 迎新服务编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditService(ServiceEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Data
                    flag = await _service.InsertServiceAsync(webModel, _context);
                }
                else
                {
                    //Update Data
                    flag = await _service.UpdateServiceAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "迎新服务信息编辑成功" : "迎新服务信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 物品信息页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchGoods(string search)
        {
            GoodsViewModel webModel = JsonUtility.ToObject<GoodsViewModel>(search);

            webModel = await _service.SearchGoodsAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SId) && webModel.SEnable == -1;

            var returnData = new
            {
                data = webModel.GoodsList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 学生疑问页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchQuestion(string search)
        {
            QuestionViewModel webModel = JsonUtility.ToObject<QuestionViewModel>(search);

            webModel = await _service.SearchQuestionAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SAskFor) && string.IsNullOrEmpty(webModel.SDateTime) && webModel.IsReply == -1;

            var returnData = new
            {
                data = webModel.QuestionList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 迎新服务页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchService(string search)
        {
            ServiceViewModel webModel = JsonUtility.ToObject<ServiceViewModel>(search);

            webModel = await _service.SearchServiceAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SAddress) && string.IsNullOrEmpty(webModel.SDate);

            var returnData = new
            {
                data = webModel.ServiceList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 回复学生疑问信息页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Reply(QuestionReplyViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {

PSU.Site/Areas/Instructor/Controllers/QuestionController.cs
//-----------------------------------------------------------------------
// <copyright file= "QuestionController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018/3/7 星期三 13:13:34
// Modified by:
// Description: Instructor-Question-控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Instructor;
using PSU.Model.Areas.Instructor.Question;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Instructor
{
    [Area("Instructor")]
    [Authorize(Policy = "Instructor")]
    public class QuestionController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IQuestionService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public QuestionController(IQuestionService service, ILogger<QuestionController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 学生疑问数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }

        /// <summary>
        /// 回复疑问信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Reply(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var webModel = await _service.GetQuestionAsync(Convert.ToInt64(id), _context);
                return View(webModel);
            }
            return Redirect("Information");
        }

        #endregion

        #region Service

        /// <summary>
        /// 学生疑问页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchQuestion(string search)
        {
            QuestionViewModel webModel = JsonUtility.ToObject<QuestionViewModel>(search);

            webModel = await _service.SearchQuestionAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SDateTime) && webModel.IsReply == -1;

            var returnData = new
            {
                data = webModel.QuestionList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 回复学生疑问信息页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Reply(QuestionReplyViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    return Json(new
                    {
                        success = false,
                        msg = "回复学生疑问信息失败,问题编号为空"
                    });
                }
                else
                {
                    //Update Question
                    flag = await _service.ReplyQuestionAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "回复学生疑问信息成功" : "回复学生疑问信息失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        #endregion
    }
}

PSU.Site/Areas/Administrator/Views/Admission/EditGoods.cshtml
@model PSU.Model.Areas.Administrator.Admission.GoodsEditViewModel
@using PSU.Model.Areas
@{
    Layout = null;
    ViewData["Title"] = "物品信息";
    ViewData["NavTitle"] = "入学信息管理";
    ViewData["CurrName"] = "物品信息维护";
}

<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" role="form" id="goods_form">
            <div class="form-group">
                <label class="col-md-2 col-xs-3 control-label no-padding-right" for="edit_name">
                    <span class="required-label">*</span> 物品名称
                </label>
                <div class="col-md-5 col-xs-10">
                    <input class="col-md-5 col-xs-12 form-control" id="edit_name" type="text" maxlength="30" asp-for="Name">
                </div>
                <label class="col-md-2 control-label no-padding-right" for="edit_enable"> 是否启用 </label>
                <div class="col-md-3">
                    <select id="edit_enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control" asp-for="IsEnabled"></select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label no-padding-right" for="edit_size"> 物品尺寸 </label>
                <div class="col-md-9">
                    <input class="col-md-5 col-xs-12 form-control" id="edit_size" type="text" maxlength="60" asp-for="Size">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label no-padding-right" for="edit_description"> 物品描述 </label>
                <div class="col-md-9">
                    <textarea id="edit_description" class="form-control" maxlength="200" rows="6" style="resize:none" asp-for="Description"></textarea>
                </div>
            </div>
            @*<div class="form-group">
                <label class="col-md-2 control-label no-padding-right" > 示意图 </label>
                <div class="col-md-10">
                    <a class="btn btn-sm btn-upload" id="iconpath">
                        <i class="fa fa-cloud-upload red2"></i>
                        <span id="pathName">图片上传</span>
                    </a>
                    <span id="fname">图片限制1M以内，仅支持GIF,BMP,PNG,JPG,JPEG图片</span>
                    <input type="hidden" id="hideUrl" value="" asp-for="ImageSrc"/>
                    <input style="visibility:hidden" type="file" id="iconupload">
                </div>
            </div>*@
            <div class="text-right">
                <a id="save" class="btn btn-success col-md-offset-2" data-id="@Model.Id">
                    <i class="ace-icon fa fa-check"></i>
                    保存
                </a>
                &nbsp; &nbsp;
                <a class="btn btn-default" asp-area="Administrator" asp-controller="Admission" asp-action="Goods">
                    <i class="fa fa-undo"></i>
                    返回
                </a>
            </div>
        </form>
    </div>
</div>

PSU.Site/Areas/Administrator/Views/Admission/EditService.cshtml
@model PSU.Model.Areas.Administrator.Admission.ServiceEditViewModel
@using PSU.Model.Areas
@{
    ViewData["Title"] = "迎新服务";
    ViewData["NavTitle"] = "入学信息管理";
    ViewData["CurrName"] = "迎新服务维护";
}

@section styles{
    <environment include="Development">
        <link href="~/css/template/bootstrap-datetimepicker.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/template/simditor.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/template/bootstrap-datetimepicker.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/template/simditor.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
}

<section class="content-header">
    <h1>
        迎新服务
        <small>Admission Service</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>
            <a asp-area="Administrator" asp-controller="Admission" asp-action="Service">
                <i class="fa fa-dashboard"></i> 入学信息
            </a>
        </li>
        <li class="active">迎新服务</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form class="form-horizontal" role="form" id="edit_form">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-default">
                            <div class="box-body">
                                <div class="form-group">
                                    <label class="col-md-2 col-xs-3 control-label no-padding-right" for="name">
                                        <span class="required-label">*</span> 服务名称
                                    </label>
                                    <div class="col-md-4 col-xs-9">
                                        <input class="form-control" id="name" type="text" maxlength="20" asp-for="Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="starttime">
                                        <span class="required-label">*</span> 开始时间
                                    </label>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <input id="starttime" class="form-control date-picker" type="text" readonly asp-for="StartTime" />
                                            <span class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <label class="col-md-2 control-label no-padding-right" for="endtime">
                                        <span class="required-label">*</span> 结束时间
                                    </label>
                                    <div class="col-md-4">
                                        <div class="input-group">
                                            <input id="endtime" class="form-control date-picker" type="text" readonly asp-for="EndTime" />
                                            <span class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="address">
                                        <span class="required-label">*</span> 服务地点
                                    </label>
                                    <div class="col-md-4">
                                        <select id="address" class="form-control" asp-for="Place">
                                            <option value="-1">请选择</option>
                                            <option value="train">火车站</option>
                                            <option value="bus">汽车站</option>
                                            <option value="school">学校</option>
                                            <option value="other">其它</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input class="form-control" id="address_custom" type="text" maxlength="20" asp-for="Address">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="enable"> 是否启用 </label>
                                    <div class="col-md-4">
                                        <select id="enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control" asp-for="IsEnabled"></select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="description"> 服务描述 </label>
                                    <div class="col-md-9">
                                        <textarea id="description" class="form-control" maxlength="500" rows="6" style="resize:none" asp-for="Description"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <div class="text-right">
                                    <a class="btn btn-success col-md-offset-2" id="save" data-id="@Model.Id">
                                        <i class="fa fa-check"></i>
                                        保存
                                    </a>
                                    &nbsp;&nbsp;
                                    <a class="btn btn-default" asp-area="Administrator" asp-controller="Admission" asp-action="Service">
                                        <i class="fa fa-undo"></i>
                                        返回
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/template/bootstrap-datetimepicker.js"></script>
        <script src="~/javascript/template/bootstrap-datetimepicker.zh-CN.js"></script>
        <script src="~/javascript/view/Administrator/editservice.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/template/datetimepicker.min.js"></script>
        <script src="~/javascript/view/Administrator/editservice.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/Admission/Question.cshtml
@{
    ViewData["Title"] = "学生疑问";
    ViewData["NavTitle"] = "入学信息管理";
    ViewData["CurrName"] = "学生疑问管理";
}

<section class="content-header">
    <h1>
        学生疑问
        <small>Student Question</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>入学信息</li>
        <li class="active">学生疑问</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label col-md-5 col-xs-4" for="askfor">提问对象：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="askfor" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label col-md-5 col-xs-4" for="datetime">提问日期：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="datetime" class="form-control date-picker" type="text" readonly />
                    <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </span>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label col-md-5 col-xs-4" for="status">问题状态：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="status" name="" class="form-control">
                        <option value="-1">请选择</option>
                        <option value="1">已回复</option>
                        <option value="0">未回复</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        @await Html.PartialAsync("_QuestionTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/question.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/question.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/Admission/Service.cshtml
@{
    ViewData["Title"] = "迎新服务";
    ViewData["NavTitle"] = "入学信息管理";
    ViewData["CurrName"] = "迎新服务维护";
}

@section styles{
    <environment include="Development">
        <link href="~/css/template/bootstrap-datetimepicker.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/template/simditor.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/template/bootstrap-datetimepicker.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/template/simditor.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
}


<section class="content-header">
    <h1>
        迎新服务
        <small>Admission Service</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>入学信息</li>
        <li class="active">迎新服务</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="name">服务名称：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="name" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-bookmark"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="address">服务地点：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="address" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-university"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="datetime">服务时间：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="datetime" class="form-control date-picker" type="text" readonly />
                    <span class="input-group-addon">
                        <i class="fa fa-calendar bigger-110"></i>
                    </span>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <a asp-area="Administrator" asp-controller="Admission" asp-action="EditService" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        @await Html.PartialAsync("_ServiceTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/template/bootstrap-datetimepicker.js"></script>
        <script src="~/javascript/template/bootstrap-datetimepicker.zh-CN.js"></script>
        <script src="~/javascript/view/Administrator/service.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/template/datetimepicker.min.js"></script>
        <script src="~/javascript/view/Administrator/service.min.js" asp-append-version="true"></script>
    </environment>
}