PSU.Site/Areas/Administrator/Controllers/SchoolController.cs
//-----------------------------------------------------------------------
// <copyright file= "SchoolController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018/2/10 星期六 15:44:50
// Modified by:
// Description: Administrator-School控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Administrator;
using PSU.Model.Areas.Administrator.School;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Administrator
{
    [Area("Administrator")]
    [Authorize(Policy = "Administrator")]
    public class SchoolController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly ISchoolService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public SchoolController(ISchoolService service, ILogger<SchoolController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 部门/院系列表页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Department()
        {
            return View();
        }

        /// <summary>
        /// 部门/院系编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditDepartment(string id)
        {
            DepartmentEditViewModel webModel = new DepartmentEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载部门/院系相关信息
                webModel = await _service.GetDepartmentAsync(Convert.ToInt64(id), _context);
            }

            return View(webModel);
        }

        /// <summary>
        /// 专业班级编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditMajorClass(string id)
        {
            MajorClassEditViewModel webModel = new MajorClassEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载部门/院系相关信息
                webModel = await _service.GetMajorClassAsync(Convert.ToInt64(id), _context);
            }

            //加载下拉列表信息
            webModel = await _service.GetDropDownListAsync(webModel, _context);

            return View(webModel);
        }

        /// <summary>
        /// 专业班级列表
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult MajorClass()
        {
            return View();
        }

        #endregion

        #region Service

        /// <summary>
        /// 部门/院系页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchDepartment(string search)
        {
            DepartmentViewModel webModel = JsonUtility.ToObject<DepartmentViewModel>(search);

            webModel = await _service.SearchDepartmentAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SId) && string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.STel);

            var returnData = new
            {
                data = webModel.DepartmentList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 专业班级页面搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchMajorClass(string search)
        {
            MajorClassViewModel webModel = JsonUtility.ToObject<MajorClassViewModel>(search);

            webModel = await _service.SearchMajorClassAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SClassName) && string.IsNullOrEmpty(webModel.SMajorName) && string.IsNullOrEmpty(webModel.SInstructorName);

            var returnData = new
            {
                data = webModel.MajorClassList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 删除部门/院系数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteDepartment(string id)
        {
            bool flag = await _service.DeleteDepartmentAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，部门/院系编号：" + id : "数据删除失败，部门/院系编号：" + id
            });
        }

        /// <summary>
        /// 删除专业班级数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteMajorClass(string id)
        {
            bool flag = await _service.DeleteMajorClassAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，专业班级编号：" + id : "数据删除失败，专业班级编号：" + id
            });
        }

        /// <summary>
        /// 部门/院系编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditDepartment(DepartmentEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Department
                    flag = await _service.InsertDepartmentAsync(webModel, _context);
                }
                else
                {
                    //Update Department
                    flag = await _service.UpdateDepartmentAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "部门/院系信息编辑成功" : "部门/院系信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 专业班级编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditMajorClass(MajorClassEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Major Class
                    flag = await _service.InsertMajorClassAsync(webModel, _context);
                }
                else
                {
                    //Update Major Class
                    flag = await _service.UpdateMajorClassAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "专业班级信息编辑成功" : "专业班级信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        #endregion
    }
}

PSU.Site/Areas/Administrator/Views/School/Department.cshtml
@model PSU.Model.Areas.Administrator.School.DepartmentViewModel
@{
    ViewData["Title"] = "部门信息";
    ViewData["NavTitle"] = "学校信息管理";
    ViewData["CurrName"] = "部门信息维护";
}

<section class="content-header">
    <h1>
        院系/部门信息
        <small>Department Information</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>学校信息</li>
        <li class="active">院系/部门信息</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="id">院系编号：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="id" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-id-badge"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="name">院系名称：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="name" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-pencil-square-o"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="tel">联系电话：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="tel" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-phone"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <a asp-area="Administrator" asp-controller="School" asp-action="EditDepartment" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        @await Html.PartialAsync("_DepartmentTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/department.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/department.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/School/EditDepartment.cshtml
@model PSU.Model.Areas.Administrator.School.DepartmentEditViewModel
@using PSU.Model.Areas
@{
    ViewData["Title"] = "部门信息";
    ViewData["NavTitle"] = "学校信息管理";
    ViewData["CurrName"] = "部门信息维护";
}

@section styles{
    <environment include="Development">
        <link href="~/css/template/simditor.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/template/simditor.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
}

<section class="content-header">
    <h1>
        院系/部门信息
        <small>Department Information</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>学校信息</li>
        <li class="active">
            <a asp-area="Administrator" asp-controller="School" asp-action="Department">
                院系/部门信息
            </a>
        </li>
        <li class="active">编辑</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form class="form-horizontal" role="form" id="department_form">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-default">
                            <div class="box-body">
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="name">
                                        <span class="required-label">*</span> 部门/院系名称
                                    </label>
                                    <div class="col-md-3">
                                        <input class="form-control" id="name" type="text" placeholder="" asp-for="Name" maxlength="20">
                                    </div>
                                    <label class="col-md-2 control-label no-padding-right" for="tel">
                                        <span class="required-label">*</span> 联系电话
                                    </label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="text" class="form-control" id="tel" asp-for="Tel" maxlength="20"/>
                                            <span class="input-group-addon">
                                                <i class="fa fa-phone fa-flip-horizontal grey"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="weibo"> 官方微博 </label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input id="weibo" class="form-control" type="text" asp-for="Weibo" maxlength="50"/>
                                            <span class="input-group-addon">
                                                <i class="fa fa-weibo text-red"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <label class="col-md-2 control-label no-padding-right" for="email">电子邮箱</label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="email" id="email" class="form-control" asp-for="Email" />
                                            <span class="input-group-addon">
                                                <i class="fa fa-envelope text-yellow"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="wechat"> 公众号 </label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="text" id="wechat" class="form-control" asp-for="Wechat" maxlength="50"/>
                                            <span class="input-group-addon">
                                                <i class="fa fa-weixin text-green"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <label class="col-md-2 control-label no-padding-right" for="qq">官方QQ</label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="text" id="qq" class="form-control" asp-for="QQ" maxlength="20"/>
                                            <span class="input-group-addon">
                                                <i class="fa fa-qq fa-flip-horizontal text-light-blue"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="enable"> 是否为部门 </label>
                                    <div class="col-md-3">
                                        <select id="branch" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Branch))" class="form-control" asp-for="IsBranch"></select>
                                    </div>
                                    <label class="col-md-2 control-label no-padding-right" for="enable"> 是否启用 </label>
                                    <div class="col-md-3">
                                        <select id="enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control" asp-for="IsEnabled"></select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label no-padding-right" for="address">办公地址</label>
                                    <div class="col-md-5">
                                        <div class="input-group">
                                            <input type="text" id="address" class="form-control" asp-for="Address" maxlength="100"/>
                                            <span class="input-group-addon">
                                                <i class="fa fa-map-marker"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-solid">
                            <div class="box box-header">
                                <div class="box-title">详细信息</div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-md-12 col-xs-12">
                                            <textarea id="editor" class="form-control" asp-for="Introduction" maxlength="500"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="text-right">
                        <a class="btn btn-success" id="save" data-id="@Model.Id">
                            <i class="fa fa-check"></i>
                            保存
                        </a>
                        &nbsp;&nbsp;
                        <a class="btn btn-default" asp-area="Administrator" asp-controller="School" asp-action="Department">
                            <i class="fa fa-undo"></i>
                            返回
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/template/module.js"></script>
        <script src="~/javascript/template/hotkeys.js"></script>
        <script src="~/javascript/template/uploader.js"></script>
        <script src="~/javascript/template/simditor.js"></script>
        <script src="~/javascript/view/Administrator/editdepartment.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/editdepartment.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/School/MajorClass.cshtml
@model PSU.Model.Areas.Administrator.School.MajorClassViewModel
@{
    ViewData["Title"] = "专业班级";
    ViewData["NavTitle"] = "学校信息管理";
    ViewData["CurrName"] = "专业班级维护";
}

<section class="content-header">
    <h1>
        专业班级
        <small>Major Class</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>学校信息</li>
        <li class="active">专业班级</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="className">班级名称：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="className" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-pencil-square-o"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="majorName">专业名称：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="majorName" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-id-badge"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="instructorName">导员姓名：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="instructorName" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-user"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <a asp-area="Administrator" asp-controller="School" asp-action="EditMajorClass" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        @await Html.PartialAsync("_MajorClassTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/majorclass.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/majorclass.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/School/_DepartmentTablePartial.cshtml
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="department-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">编号</th>
                        <th class="text-center">院系名称</th>
                        <th class="text-center">联系电话</th>
                        <th class="text-center">电子邮箱</th>
                        <th class="text-center">微信公众号</th>
                        <th class="text-center">是否为部门</th>
                        <th class="text-center">操作</th>
                    </tr>
                </thead>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>

PSU.Site/Areas/Administrator/Views/School/_MajorClassTablePartial.cshtml
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="majorclass-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">编号</th>
                        <th class="text-center">班级名称</th>
                        <th class="text-center">专业代码</th>
                        <th class="text-center">专业名称</th>
                        <th class="text-center">级数</th>
                        <th class="text-center">辅导员姓名</th>
                        <th class="text-center">是否启用</th>
                        <th class="text-center">操作</th>
                    </tr>
                </thead>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>