PSU.Site/Areas/Administrator/Controllers/DormitoryController.cs
//-----------------------------------------------------------------------
// <copyright file= "DormitoryController.cs">
//     Copyright (c) Qing. All rights reserved.
// </copyright>
// Author: Qing
// Date Created: 2018/2/10 星期六 15:43:36
// Modified by:
// Description: Administrator-Dormitory控制器
//-----------------------------------------------------------------------
using PSU.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PSU.EFCore;
using PSU.IService.Areas.Administrator;
using PSU.Model.Areas.Administrator.Dormitory;
using PSU.Utility;
using PSU.Utility.Web;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PSU.Controllers.Areas.Administrator
{
    [Area("Administrator")]
    [Authorize(Policy = "Administrator")]
    public class DormitoryController : DanvicController
    {
        #region Initialize

        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IDormitoryService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public DormitoryController(IDormitoryService service, ILogger<DormitoryController> logger, IHttpContextAccessor httpContextAccessor, ApplicationDbContext context)
        {
            _service = service;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _context = context;
            CurrentUser.Configure(_httpContextAccessor);
        }

        #endregion

        #region View

        /// <summary>
        /// 宿舍楼列表页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Building()
        {
            return View();
        }

        /// <summary>
        /// 宿舍类型列表页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Bunk()
        {
            return View();
        }

        /// <summary>
        /// 宿舍类型编辑页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditBunk(string id)
        {
            BunkEditViewModel webModel = new BunkEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载宿舍楼相关信息
                webModel = await _service.GetBunkAsync(Convert.ToInt64(id), _context);
            }

            return View(webModel);
        }

        /// <summary>
        /// 宿舍编辑页面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditInformation(string id)
        {
            InformationEditViewModel webModel = new InformationEditViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                //编辑信息，加载宿舍相关信息
                webModel = await _service.GetInformationAsync(Convert.ToInt64(id), _context);
            }

            //加载下拉列表信息
            webModel = await _service.GetDropDownListAsync(webModel, _context);

            return View(webModel);
        }

        /// <summary>
        /// 宿舍信息列表页
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }
        #endregion

        #region Service

        /// <summary>
        /// 删除宿舍楼数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteBuilding(string id)
        {
            bool flag = await _service.DeleteBuildingAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，宿舍楼编号：" + id : "数据删除失败，宿舍楼编号：" + id
            });
        }

        /// <summary>
        /// 删除宿舍类型数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteBunk(string id)
        {
            bool flag = await _service.DeleteBunkAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，宿舍类型编号：" + id : "数据删除失败，宿舍类型编号：" + id
            });
        }

        /// <summary>
        /// 删除宿舍数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> DeleteInformation(string id)
        {
            bool flag = await _service.DeleteInformationAsync(Convert.ToInt64(id), _context);

            return Json(new
            {
                sueeess = flag,
                msg = flag ? "数据删除成功，宿舍编号：" + id : "数据删除失败，宿舍编号：" + id
            });
        }

        /// <summary>
        /// 宿舍楼编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditBuilding(BuildingEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Building
                    flag = await _service.InsertBuildingAsync(webModel, _context);
                }
                else
                {
                    //Update Building
                    flag = await _service.UpdateBuildingAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "宿舍楼信息编辑成功" : "宿舍楼信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 宿舍类型编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditBunk(BunkEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Building
                    flag = await _service.InsertBunkAsync(webModel, _context);
                }
                else
                {
                    //Update Building
                    flag = await _service.UpdateBunkAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "宿舍类型信息编辑成功" : "宿舍类型信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 宿舍编辑页面
        /// </summary>
        /// <param name="webModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditInformation(InformationEditViewModel webModel)
        {
            if (ModelState.IsValid)
            {
                bool flag;
                if (string.IsNullOrEmpty(webModel.Id))
                {
                    //Add Dorm Information
                    flag = await _service.InsertInformationAsync(webModel, _context);
                }
                else
                {
                    //Update Dorm Information
                    flag = await _service.UpdateInformationAsync(webModel, _context);
                }

                return Json(new
                {
                    success = flag,
                    msg = flag ? "宿舍信息编辑成功" : "宿舍信息编辑失败"
                });
            }

            return Json(new
            {
                success = false,
                msg = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors).FirstOrDefault().ErrorMessage
            });
        }

        /// <summary>
        /// 宿舍楼搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchBuilding(string search)
        {
            BuildingViewModel webModel = JsonUtility.ToObject<BuildingViewModel>(search);

            webModel = await _service.SearchBuildingAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SId) && webModel.SType == 0 && webModel.SEnable == 9;

            var returnData = new
            {
                data = webModel.BuildingList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 宿舍楼搜索
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SearchBunk(string search)
        {
            BunkViewModel webModel = JsonUtility.ToObject<BunkViewModel>(search);

            webModel = await _service.SearchBunkAsync(webModel, _context);

            //Search Or Init
            bool flag = string.IsNullOrEmpty(webModel.SName) && string.IsNullOrEmpty(webModel.SDirection) && webModel.SEnable == -1;

            var returnData = new
            {
                data = webModel.BunkList,
                limit = webModel.Limit,
                page = flag ? webModel.Page : 1,
                total = webModel.Total
            };

            return Json(returnData);
        }

        /// <summary>
        /// 宿舍搜索

PSU.Site/Areas/Administrator/Views/Dormitory/Building.cshtml
@using PSU.Model.Areas
@{
    ViewData["Title"] = "宿舍楼信息";
    ViewData["NavTitle"] = "宿舍信息管理";
    ViewData["CurrName"] = "基础信息维护";
}

<section class="content-header">
    <h1>
        基础信息维护
        <small>Building Information</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>宿舍信息</li>
        <li class="active">基础信息维护</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="code">编号：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="code" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-building"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="type">建筑类型：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="type" name="" class="form-control">
                        <option value="0">请选择</option>
                        <option value="1">男生寝室</option>
                        <option value="2">女生寝室</option>
                        <option value="3">混合寝室</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="enable">是否启用：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="enable" name="" class="form-control">
                        <option value="9">请选择</option>
                        <option value="1">启用</option>
                        <option value="0">未启用</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <button data-toggle="modal" data-target="#myModal" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        @await Html.PartialAsync("_BuildingTablePartial")
    </div>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">编辑宿舍信息</h5>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="edit_id" value=""/>
                    <form method="post" class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-md-3 col-xs-3 control-label no-padding-right" for="edit_name"> 宿舍楼名称： </label>
                            <div class="col-md-3 col-xs-9">
                                <input class="col-md-5 col-xs-12 form-control" id="edit_name" type="text" maxlength="20">
                            </div>
                            <label class="col-md-3 control-label no-padding-right" for="edit_floor">总楼层：</label>
                            <div class="col-md-2">
                                <input class="form-control" id="edit_floor" type="number" min="1">
                            </div>
                            <label class="control-label" for="floor">层</label>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label no-padding-right" for="edit_type">宿舍楼类型：</label>
                            <div class="col-md-3">
                                <select id="edit_type" asp-items="@Html.GetEnumSelectList(typeof(EnumType.BuildingType))" class="form-control"></select>
                            </div>
                            <label class="col-md-3 col-xs-3 control-label no-padding-right" for="edit_enable"> 是否启用： </label>
                            <div class="col-md-3 col-xs-9">
                                <select id="edit_enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control"></select>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" id="add">提交更改</button>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/building.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/building.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/Dormitory/Bunk.cshtml
@{
    ViewData["Title"] = "宿舍类型";
    ViewData["NavTitle"] = "宿舍信息管理";
    ViewData["CurrName"] = "宿舍类型维护";
}

<section class="content-header">
    <h1>
        宿舍类型
        <small>Dormitory Type</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>宿舍信息</li>
        <li class="active">宿舍类型</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="name">类型名称：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="name" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-bed"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="direction">寝室朝向：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="direction" name="" class="form-control">
                        <option value="">请选择</option>
                        <option value="East">面朝东</option>
                        <option value="West">面朝西</option>
                        <option value="South">面朝南</option>
                        <option value="North">面朝北</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="enable">是否启用：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="enable" class="form-control">
                        <option value="-1">请选择</option>
                        <option value="1">启用</option>
                        <option value="0">未启用</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <a id="add" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        @await Html.PartialAsync("_BunkTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/bunk.js"></script>
        <script src="~/javascript/template/ajaxupload.js"></script>
        <script src="~/javascript/view/Administrator/editbunk.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/bunk.min.js" asp-append-version="true"></script>
        <script src="~/javascript/view/Administrator/editbunk.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/Dormitory/EditBunk.cshtml
@model PSU.Model.Areas.Administrator.Dormitory.BunkEditViewModel
@using PSU.Model.Areas
@{
    Layout = null;
    ViewData["Title"] = "宿舍类型";
    ViewData["NavTitle"] = "宿舍信息管理";
    ViewData["CurrName"] = "宿舍类型维护";
}

<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" role="form" id="majorclass_form">
            <div class="form-group">
                <label class="col-md-2 col-xs-3 control-label no-padding-right" for="edit_name">
                    <span class="required-label">*</span> 类型名称
                </label>
                <div class="col-md-4 col-xs-9">
                    <input class="col-md-5 col-xs-12 form-control" id="edit_name" type="text" maxlength="20" asp-for="Name">
                </div>
                <label class="col-md-2 control-label no-padding-right" for="edit_number"> 可容纳人数 </label>
                <div class="col-md-2">
                    <input class="form-control" id="edit_number" type="number" min="1" asp-for="Number">
                </div>
                <label class="control-label" for="edit_number">人</label>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label no-padding-right" for="edit_toward"> 寝室朝向 </label>
                <div class="col-md-4">
                    <select id="edit_toward" asp-items="@Html.GetEnumSelectList(typeof(EnumType.BunkToward))" class="form-control" asp-for="Toward"></select>
                </div>
                <label class="col-md-2 control-label no-padding-right" for="edit_enable"> 是否启用 </label>
                <div class="col-md-4">
                    <select id="edit_enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control" asp-for="IsEnabled"></select>
                </div>
            </div>
            @*<div class="form-group">
                <label class="col-md-2 control-label no-padding-right"> 示意图 </label>
                <div class="col-md-10">
                    <a class="btn btn-sm btn-upload" id="iconpath">
                        <i class="fa fa-cloud-upload red2"></i>
                        <span id="pathName">图片上传</span>
                    </a>
                    <span id="fname">图片限制1M以内，仅支持GIF,BMP,PNG,JPG,JPEG图片</span>
                    <input type="hidden" id="edit_hideUrl" value="" />
                    <input style="visibility:hidden" type="file" id="iconupload">
                </div>
            </div>*@
            <div class="text-right">
                <a id="save" class="btn btn-success col-md-offset-2" data-id="@Model.Id">
                    <i class="ace-icon fa fa-check"></i>
                    保存
                </a>
                &nbsp; &nbsp;
                <a class="btn btn-default" asp-area="Administrator" asp-controller="Dormitory" asp-action="Bunk">
                    <i class="fa fa-undo"></i>
                    返回
                </a>
            </div>
        </form>
    </div>
</div>

PSU.Site/Areas/Administrator/Views/Dormitory/EditInformation.cshtml
@model PSU.Model.Areas.Administrator.Dormitory.InformationEditViewModel
@using PSU.Model.Areas
@{
    Layout = null;
    ViewData["Title"] = "寝室信息";
    ViewData["NavTitle"] = "宿舍信息管理";
    ViewData["CurrName"] = "寝室信息维护";
}

<div class="row">
    <div class="col-md-12">
        <form method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-md-2 col-xs-3 control-label no-padding-right" for="edit_name">
                    <span class="required-label">*</span>宿舍号
                </label>
                <div class="col-md-4 col-xs-9">
                    <input class="col-md-5 col-xs-12 form-control" id="edit_name" type="text" maxlength="20" asp-for="Name">
                </div>
                <label class="col-md-2 col-xs-3 control-label no-padding-right" for="edit_building"> 所属宿舍楼 </label>
                <div class="col-md-4 col-xs-9">
                    <select id="edit_building" class="form-control" asp-for="BuildingId">
                        <option value="-1">请选择</option>
                        @if (Model.BuildingList != null && Model.BuildingList.Any())
                        {
                            foreach (var item in Model.BuildingList.AsReadOnly())
                            {
                                if (item.Id == Model.BuildingId)
                                {
                                    <option value="@item.Id" selected> @item.Name </option>
                                }
                                else
                                {
                                    <option value="@item.Id"> @item.Name </option>
                                }
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label no-padding-right" for="edit_floor"> 所在楼层 </label>
                <div class="col-md-2">
                    <input class="form-control" id="edit_floor" type="number" min="1" asp-for="Floor">
                </div>
                <label class="control-label" for="edit_floor">层</label>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label no-padding-right" for="edit_bunk"> 宿舍类型 </label>
                <div class="col-md-4">
                    <select id="edit_bunk" class="form-control" asp-for="BunkId">
                        <option value="-1">请选择</option>
                        @if (Model.BunkList != null && Model.BunkList.Any())
                        {
                            foreach (var item in Model.BunkList.AsReadOnly())
                            {
                                if (item.Id == Model.BunkId)
                                {
                                    <option value="@item.Id" data_count="@item.Count" selected> @item.Name </option>
                                }
                                else
                                {
                                    <option value="@item.Id" data_count="@item.Count"> @item.Name </option>
                                }
                            }
                        }
                    </select>
                </div>
                <label class="col-md-2 control-label no-padding-right" for="edit_count"> 可容纳人数 </label>
                <div class="col-md-2">
                    <input class="form-control" id="edit_count" type="number" min="1" asp-for="Count">
                </div>
                <label class="control-label" for="floor">人</label>
            </div>
            <div class="form-group">
                <label class="col-md-2 col-xs-3 control-label no-padding-right" for="enable"> 是否启用 </label>
                <div class="col-md-4 col-xs-9">
                    <select id="enable" asp-items="@Html.GetEnumSelectList(typeof(EnumType.Enable))" class="form-control" asp-for="IsEnabled"></select>
                </div>
            </div>
            <div class="text-right">
                <a class="btn btn-success col-md-offset-2" id="save" data-id="@Model.Id">
                    <i class="fa fa-check"></i>
                    保存
                </a>
                &nbsp; &nbsp;
                <a class="btn btn-default" asp-area="Administrator" asp-controller="Dormitory" asp-action="Information">
                    <i class="fa fa-undo"></i>
                    返回
                </a>
            </div>
        </form>
    </div>
</div>

PSU.Site/Areas/Administrator/Views/Dormitory/Information.cshtml
@{
    ViewData["Title"] = "寝室信息";
    ViewData["NavTitle"] = "宿舍信息管理";
    ViewData["CurrName"] = "寝室信息维护";
}

<section class="content-header">
    <h1>
        寝室信息
        <small>Dormitory Information</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a asp-area="Administrator" asp-controller="Home" asp-action="Index">
                <i class="fa fa-dashboard"></i> 首页
            </a>
        </li>
        <li>宿舍信息</li>
        <li class="active">寝室信息</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="name">宿舍号：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="name" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-id-card"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="type">宿舍类型：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <input id="type" type="text" class="form-control">
                    <div class="input-group-addon">
                        <i class="fa fa-building"></i>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label no-padding-right col-md-5 col-xs-4" for="floor">所在楼层：</label>
                <div class="input-group col-md-7 col-xs-8">
                    <select id="floor" name="" class="form-control">
                        <option value="-1">请选择</option>
                        @for (int i = 1; i <= 10; i++)
                        {
                            <option value="@i">@i 层</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group col-md-3">
                <button id="search" class="btn btn-dropbox btn-flat col-md-4">
                    <i class="fa fa-search"></i>&nbsp;搜索
                </button>
                <a id="add" class="btn btn-success btn-flat col-md-4 col-xs-offset-1 col-md-offset-1">
                    <i class="fa fa-plus"></i>&nbsp;新建
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        @await Html.PartialAsync("_InformationTablePartial")
    </div>
</section>

@section scripts{
    <environment include="Development">
        <script src="~/javascript/view/Administrator/dorm.js" asp-append-version="true"></script>
        <script src="~/javascript/view/Administrator/editinformation.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/javascript/view/Administrator/dorm.min.js" asp-append-version="true"></script>
        <script src="~/javascript/view/Administrator/editinformation.min.js" asp-append-version="true"></script>
    </environment>
}

PSU.Site/Areas/Administrator/Views/Dormitory/_BuildingTablePartial.cshtml
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="building-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">编号</th>
                        <th class="text-center">名称</th>
                        <th class="text-center">总楼层</th>
                        <th class="text-center">类型</th>
                        <th class="text-center">创建人</th>
                        <th class="text-center">创建时间</th>
                        <th class="text-center">是否启用</th>
                        <th class="text-center">操作</th>
                    </tr>
                </thead>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>

PSU.Site/Areas/Administrator/Views/Dormitory/_BunkTablePartial.cshtml
<div class="col-xs-12">
    <div class="box">
        <div class="box-body">
            <table id="bunk-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">编号</th>
                        <th class="text-center">宿舍类型名称</th>
                        <th class="text-center">可容纳人数</th>
                        <th class="text-center">寝室朝向</th>
                        <th class="text-center">是否启用</th>
                        <th class="text-center">操作</th>
                    </tr>
                </thead>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>